baseURL = "https://www.edwinwenink.xyz/"
languageCode = "en-us"
title = "Edwin Wenink"
theme = "one"
googleAnalytics = "UA-117420879-1"
pygmentuseclasses = true

[params]
    navigation = ["archives.md", "about.md"]
