baseURL = "https://www.edwinwenink.xyz/"
languageCode = "en-us"
title = "Archive Fever by Edwin Wenink"
googleAnalytics = "UA-117420879-1"
pygmentuseclasses = true
github_username = "EdwinWenink"
relativeURLs = true
disablePathToLower = false
enableGitInfo = true
paginate = 5

[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
	recaptcha_sitekey = "6LeIcYQUAAAAAEmaP89swNtAL90F0KwpsCyX-l7i"
	staticman_api = "http://77.249.145.182:1234/v2/entry/EdwinWenink/personal_website/master/comments"
