baseURL = "https://www.edwinwenink.xyz/"
languageCode = "en-us"
title = "Archive Fever by Edwin Wenink"
googleAnalytics = "UA-117420879-1"
pygmentuseclasses = true
github_username = "EdwinWenink"
relativeURLs = true
disablePathToLower = false
enableGitInfo = true
paginate = 5

[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    # N.B. this broke after updating to 0.71.0!
    # TODO replace with built-in [menu] option
    navigation = ["about.md", "archives.md", "authors.md", "etc/etc.md", "now.md" ]
	about = "about.md"
	archive = "archives.md"
	authors = "authors.md"
	etc = "etc.md"
    now = "now.md"
	recaptcha_sitekey = "6LeIcYQUAAAAAEmaP89swNtAL90F0KwpsCyX-l7i"
	staticman_api = "http://77.249.145.182:1234/v2/entry/EdwinWenink/personal_website/master/comments"
