baseURL = "https://www.edwinwenink.xyz/"
languageCode = "en-us"
title = "Edwin Wenink"
googleAnalytics = "UA-117420879-1"
pygmentuseclasses = true

[params]
    navigation = ["archives.md", "about.md"]
	archive = "archives.md"
	about = "about.md"
	recaptcha_sitekey = "6LeIcYQUAAAAAEmaP89swNtAL90F0KwpsCyX-l7i"


