baseURL = "https://www.edwinwenink.xyz/"
languageCode = "en-us"
title = "Edwin Wenink"
googleAnalytics = "UA-117420879-1"
pygmentuseclasses = true
github_username = "EdwinWenink"

[params]
    navigation = ["archives.md", "about.md", "etc.md", "authors.md"]
	archive = "archives.md"
	about = "about.md"
	etc = "etc.md"
	authors = "authors.md"
	recaptcha_sitekey = "6LeIcYQUAAAAAEmaP89swNtAL90F0KwpsCyX-l7i"
	staticman_api = "http://77.249.145.182:1235/v2/entry/EdwinWenink/personal_website/master/comments"

