baseURL = "https://www.edwinwenink.xyz/"
languageCode = "en-us"
title = "Edwin Wenink"
googleAnalytics = "UA-117420879-1"
pygmentuseclasses = true

[params]
    navigation = ["archives.md", "about.md"]
	archive = "archives.md"
	about = "about.md"
	recaptcha_sitekey = "6LeIcYQUAAAAAEmaP89swNtAL90F0KwpsCyX-l7i"
	staticman_api = "http://192.168.2.163:1234/v2/entry/EdwinWenink/personal_website/staticman-comments/comments"

