name: Lint

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            content/**/*.md
            !content/zettelkasten/**

